/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.example.app;

public final class R {
  public static final class color {
    public static final int colorPrimary=0x7f010000;
    public static final int colorPrimaryDark=0x7f010001;
    public static final int navigationBarColor=0x7f010002;
    public static final int windowBackground=0x7f010003;
  }
  public static final class id {
    public static final int button=0x7f020000;
  }
  public static final class layout {
    public static final int main_layout=0x7f030000;
  }
  public static final class mipmap {
    public static final int icon=0x7f040000;
  }
  public static final class style {
    public static final int ActivityTheme=0x7f050000;
    public static final int TextStyle=0x7f050001;
  }
}